[project]
name = "mag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv.sources]
pypika = { version = "0.48.9", build-system = { requires = ["setuptools<60", "wheel"] } }
